### ISSUE TITLE
Accept a test array in index.js::fetch()

### ISSUE THREAD

**Issue by ramanathanMuthuraman** [nature/webpagetest-mapper#15]
The module is awesome but instead of making a separate test definitions file to pass the test URL, Can we have an object literal which is defined in the same file. This is an enhancement and not a bug.

**Comment by philbooth** [comment]
Not sure I follow. Which file do you want the test definitions to go into?

**Comment by ramanathanMuthuraman** [comment]
Suppose, if I am write a gulp task in gulpfile.js for using this module, I should be able to give the test URL  in the gulpfile itself instead of  using a separate file like tests.json

**Comment by philbooth** [comment]
Got it now.

In case anyone wants to implement this, it just requires bypassing the call to `readJSON` if we already have an array, [in `src/options.js`](https://github.com/nature/webpagetest-mapper/blob/master/src/options.js#L186):

```js
    var tests = readJSON(options.tests, defaults.tests);
```

Recommend editing the issue title to something like "Accept a test array in index.js::fetch()'.

**Comment by ramanathanMuthuraman** [comment]
Cool.. But instead of editing in the module file.. it'll be better if this option is made configurable.

**Comment by philbooth** [comment]
I'm not sure it needs to be configurable tbh. If `options.tests` is a string, we know it is a path to a test definitions file. If `options.tests` is an array, we know it is the test definitions themselves.

Unless I'm missing something?

**Comment by ramanathanMuthuraman** [comment]
I mean.. if we can add the test of string/Array in readJSON function.. the user can pass either file path/ array. 
function readJSON (jsonPath, defaultFileName) {
    check.assert.unemptyString(defaultFileName);

    if (check.not.unemptyString(jsonPath)) {
        jsonPath = defaultFileName;
    }

    jsonPath = path.resolve(jsonPath);

    if (fs.existsSync(jsonPath) && fs.statSync(jsonPath).isFile()) {
        return JSON.parse(fs.readFileSync(jsonPath), { encoding: 'utf8' });
    }
// The condition I am trying to add
 if(jsonPath instanceOf Array)
    {
        return jsonPath;
    }
    return {};
}

**Comment by philbooth** [comment]
I wouldn't make the change inside `readJSON`, because this condition doesn't apply to the other invocations of it. I'd make it inside `options.js`, circa [line 186, at the top of `getTests`](https://github.com/nature/webpagetest-mapper/blob/master/src/options.js#L186). Something like this:

```js
var tests = options.tests;
if (! Array.isArray(tests)) {
    tests = readJSON(tests, defaults.tests);
}
```

**Comment by ramanathanMuthuraman** [comment]
That's more neat..

**Comment by GlynnPhillips** [comment]
@ramanathanMuthuraman I am now working on implementing this how @philbooth has suggested. I will let you know when we push a new version
